### ISSUE TITLE
Add possibility to run mapper several times using different databases and settings

### ISSUE THREAD

**Issue by boulund** [boulund/stag-mwc#33]
Last night I was thinking about adding the ability to run any of the mappers (e.g. BBmap or Bowtie2) several times in a workflow, using different databases and different settings. I know from personal experience that I'd probably like to map to a database containing a specific set of genes, but also map to a larger gene catalog for overall functional content assessment. Without having to actually implement distinct mapping steps for the different databases, it would be more flexible if we could configure mapping against several databases using the config file. I was thinking about putting the mapping settings in a list of databases to map against underneath the mapper configuration, e.g. in `config.yaml`:

```
#########################
# Mappers
#########################
bbmap:
    - db_name: "db_1"
      db_path: "/path/to/db1"
      min_id: 0.76
      extra: ""
      counts_table:
          annotations: ""
      featureCounts:
          annotations: "/path/to/db2.annotation.gtf"
          feature_type: "gene_id"
          attribute_type: ""
          extra: "" 
    - db_name: "db_2"
      db_path: "/path/to/db2"
      min_id: 0.98
      extra: ""
      counts_table:
          annotations: "/path/to/db2.annotation.tab"
      featureCounts:
          annotations: ""
          feature_type: ""
          attribute_type: ""
          extra: "" 
```

This would define two database to map reads against using BBMap. Additional databases can be mapped by adding more items to the list. Then, at least the way I thought of this, we would let the code in `rules/mappers/bbmap.smk` programatically generate mapping rules for each of the reference databases. For example, something like this:

```
for bbmap_config in config["bbmap"]:
    bbmap_output_folder = OUTDIR/"bbmap/{db_name}".format(db_name=bbmap_config["db_name"])
    bbmap_log_dir = LOGDIR/"bbmap/{db_name}".format(db_name=bbmap_config["db_name"])
    rule :
        """BBMap against {db_name}""".format(bbmap_config["db_name"])
        input:
            read1=OUTDIR/"filtered_human/{sample}_R1.filtered_human.fq.gz",
            read2=OUTDIR/"filtered_human/{sample}_R2.filtered_human.fq.gz",
        output:
            sam=bbmap_output_folder/"{sample}.sam.gz",
            covstats=bbmap_output_folder/"{sample}.covstats.txt",
            rpkm=bbmap_output_folder/"{sample}.rpkm.txt",
        log:
            stdout=str(bbmap_log_dir/"{sample}.bbmap.stdout.log"),
            stderr=str(bbmap_log_dir/"{sample}.bbmap.statsfile.txt"),
        shadow: "shallow"
        conda: "../../envs/stag-mwc.yaml"
        message: "BBMap of {{sample}} against {db_name}".format(db_name=bbmap_config["db_name"])
        threads: 8
        params:
            db_path=bbmap_config["db_path"],
            min_id=bbmap_config["min_id"],
            extra=bbmap_config["extra"],
        shell:
            """
            ...
            """
```
It might not be the prettiest, but it should get the job done. One potential issue, however, is that it is currently not possible to programatically define rule names in Snakemake, an issue which is sidestepped by producing anonymous rules (i.e. rules without a name), for which Snakemake will come up with its own names, which might not be entirely descriptive... But that's a minor issue, in my opinion. At least if you consider that the rule description can still contain the importat information. Also, the log message when the rule is executed could be modified to include the relevant information.
